from .web_tool import TOOL_WEB_NAVIGATE, TOOL_WEB_CLICK, TOOL_WEB_INPUT, TOOL_WEB_WAIT, TOOL_WEB_CHECK, TOOL_WEB_SCREENSHOT
from .desktop_tool import TOOL_DESKTOP_CLICK, TOOL_DESKTOP_INPUT, TOOL_DESKTOP_SCREENSHOT, TOOL_DESKTOP_FIND_WINDOW
from .ssh_tool import TOOL_SSH_EXECUTE, TOOL_SSH_GET_LOG
from .vision_tool import TOOL_VISION_ANALYZE, TOOL_VISION_COMPARE
from .knowledge_tool import TOOL_KNOWLEDGE_SEARCH, TOOL_KNOWLEDGE_GET_TOPOLOGY, TOOL_KNOWLEDGE_GET_LOCATOR, TOOL_KNOWLEDGE_CACHE_LOCATOR

ALL_TOOLS = [
    TOOL_WEB_NAVIGATE, TOOL_WEB_CLICK, TOOL_WEB_INPUT, TOOL_WEB_WAIT, TOOL_WEB_CHECK, TOOL_WEB_SCREENSHOT,
    TOOL_DESKTOP_CLICK, TOOL_DESKTOP_INPUT, TOOL_DESKTOP_SCREENSHOT, TOOL_DESKTOP_FIND_WINDOW,
    TOOL_SSH_EXECUTE, TOOL_SSH_GET_LOG,
    TOOL_VISION_ANALYZE, TOOL_VISION_COMPARE,
    TOOL_KNOWLEDGE_SEARCH, TOOL_KNOWLEDGE_GET_TOPOLOGY, TOOL_KNOWLEDGE_GET_LOCATOR, TOOL_KNOWLEDGE_CACHE_LOCATOR,
]

TOOL_BY_NAME = {t["name"]: t for t in ALL_TOOLS}
